version: '3.8'
services:
  # 1. Ο "Μεσολαβητής" (MQTT Broker)
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

  # 2. Η Βάση Δεδομένων
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: deafnav_db
    ports:
      - "5432:5432"
